---
:concurrency: 5
staging:
  :concurrency: 10
production:
  :concurrency: 10
:queues:
  - [indexation, 4]
  - [notifications, 4]
  - [scheduler, 3]
  - [mailers, 2]
  - default
:schedule:
  reindex_events:
    every: 1h
    class: ReindexRecordsJob
    queue: scheduler
    args: 'Event'
    description: 'This job will reindex events with algolia'
  events_started:
    every: 5m
    class: EventsStartedJob
    queue: scheduler
    description: 'This job will remove pending submissions of started events'
  notifications_sender:
    every: 1h
    class: NotificationsSenderJob
    queue: scheduler
    description: 'This job will send a batch of notifications for each user in one email'
  remind_flexible_events:
    every: 5m
    class: RemindFlexibleEvents
    queue: scheduler
    description: 'This job will send a reminder to flexible events close to the limit'
  confirm_flexible_events:
    every: 5m
    class: ConfirmFlexibleEvents
    queue: scheduler
    description: 'This job will automatically confirm flexible events close to the limit'
:scheduler:
  :listened_queues_only:
